site_name: IsaacStack
site_description: "Practical Isaac Sim and Isaac Lab code examples, extensions, and workflows."
site_author: "Aldrin Inbaraj"
site_url: https://isaacstack.github.io

theme:
  name: material
  logo: assets/misc/logo.png
  favicon: assets/misc/logo.png
  palette:
    scheme: light 
    primary: green
    accent: black
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Blog:
      - Blog Home: blog/index.md
      - Getting Started with IsaacStack: blog/post1.md
      - Rigging the Robotiq 2F-85 Gripper: tutorials/post2.md
      - UR5e + Robotiq Extension: extensions/post3.md
  - Assets: assets/index.md
  - Snippets: snippets/index.md
  - Extensions:
      - UR5e + Robotiq Extension: extensions/post3.md
  - Tutorials:
      - Rigging the Robotiq 2F-85 Gripper: tutorials/post2.md
  - Contact: contact.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition

extra_css:
  - stylesheets/extra.css
