site_name: IsaacStack
site_description: "Practical Isaac Sim and Isaac Lab code examples, extensions, and workflows."
site_author: "Aldrin Inbaraj"
site_url: https://isaacstack.github.io

theme:
  name: material
  logo: assets/misc/logo.png
  favicon: assets/misc/logo.png
  palette:    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: green
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - content.code.copy
    - toc.integrate

nav:
  - Home: index.md
  - Blog:
      - Blog Home: blog/index.md
      - Getting Started with IsaacStack: blog/post1.md
      - Rigging the Robotiq 2F-85 Gripper: tutorials/post2.md
      - UR5e + Robotiq Extension: extensions/post3.md
  - Assets: assets/index.md
  - Snippets: snippets/index.md
  - Extensions:
      - UR5e + Robotiq Extension: extensions/post3.md
  - Tutorials:
      - Rigging the Robotiq 2F-85 Gripper: tutorials/post2.md
  - Contact: contact.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
# extra_css: #for a line between page and content list of the page if "toc.integrate" is not used 
#   - stylesheets/extra.css

plugins:
  - search

  